dbname: dev-db

spring:
  datasource:
    url: jdbc:h2:mem:readinglist;DB_CLOSE_ON_EXIT=FALSE
    username: dbuser # dbpass
    password: "{cipher}96490261367abfca52f1c98f1d766ceb280c20ea9485208da40f6c965bf026e1"
    driver-class-name: org.h2.Driver